Natural  Language Processing is all obout analysing text and this can be book, text doc, html web page, etc. And it is a branch of Machine learning we do some predective analysis on text. Here we analyse the text review and sort the if the review is positive or negative. This will be the general algorith and we can also apply the same to analyse the book and other sources.

In [55]:
#let start with algorithem
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [56]:
#loading the dataset
dataset = pd.read_csv("Restaurant_Reviews.tsv", delimiter = "\t", quoting = 3)


In [57]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
Review    1000 non-null object
Liked     1000 non-null int64
dtypes: int64(1), object(1)
memory usage: 15.7+ KB
None


In [58]:
print(dataset.head())

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1


In [59]:
print(dataset.describe())

            Liked
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000


""" cleaning the dataset is like preparing our dataset to apply our machine learning model. The step include:
1. Get rid of the punctuations as this create many confusions of the words and difficult to understand.
2. steaming the dataset like sorting some words like loved, liked and converting them to ove and like respectively.
3. converting all the uppercase letter to lower case letter.
4. get reid of the nuumbers, unless they are not relevent.
5. we will construct columns for each associated word and will count if it appears in the review or not. this will create more
zeros in our columns.
6. we will use sparse matrix as most of the part we will be having 0's as most are new words"""



In [60]:
#cleaning the texts
#importing re as its is most used library to clean text.
import re
review = re.sub("[^a-zA-Z]", " ",  dataset["Review"][0])
#here re.sub sort the text on by the letter from A to Z and get free of all the other punctuation, nubers, etc.
"""here our input to the sub command is "[^a-zA-Z]" which means we want everything to remove or sort expect the letter
from a to z and also capital letters from A to Z, also here zA is not seperated and this create a problem and
so to sort that we add a new paramer space """



'here our input to the sub command is "[^a-zA-Z]" which means we want everything to remove or sort expect the letter\nfrom a to z and also capital letters from A to Z, also here zA is not seperated and this create a problem and\nso to sort that we add a new paramer space '

In [61]:
print(review)

Wow    Loved this place 


In [62]:
# the next process will be to convert all the letter to a lower case letter
review = review.lower()
print(review)

wow    loved this place 


In [63]:
# now in the next process we will get rid of word which are of no use to us to judge the review like article, prepositions, etc.
#we need a library which contain most functions of NLP calles nltk
import nltk
nltk.download("stopwords")


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rahul007\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [64]:
""" now we will run a for loop for all the review for the same process we done above for 1st review"""
review =review.split()
print(review)


['wow', 'loved', 'this', 'place']


In [65]:
from nltk.corpus import stopwords
review = [word for word in review if not word in set(stopwords.words("english"))]
#the set function is used to speedup the algo as it guide fot the set of words in the list
print(review)

['wow', 'loved', 'place']


In [66]:
#now appling stemming. we need to import porterstemmer
from nltk.stem.porter import PorterStemmer
#we will redesign our algorithem as the above process was to make understanding and now we can have a fun algorithem here.
ps = PorterStemmer()
review = [ps.stem(word) for word in review if not word in set(stopwords.words("english"))]
print(review)

['wow', 'love', 'place']


In [67]:
#we will make a list containg all the words and so we use join command with space as to seperate the words for join in single word.
review = " ".join(review)
print(review)

wow love place


In [68]:
#the same process we will perform for all 1000 review.
#we will make a list for all 1000 reviews names corpus
corpus = []
for i in range(0, 1000):
    review_1 = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review_1 = review_1.lower()
    review_1 = review_1.split()
    ps = PorterStemmer()
    review_1 = [ps.stem(word) for word in review_1 if not word in set(stopwords.words('english'))]
    review_1 = ' '.join(review_1)
    corpus.append(review_1)
    

In [69]:
corpus[:10]

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch']

In [70]:
#creating a bag of word model, appluing the machine learning model and tranforming and predicting.
""" we will make a table containing all the review in one column. And then we choose a specific word and count the 
number of times the specific word appeared in the review """
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
#we can do use stemming , sorting and many other things in countvectorizer but can be more efficient doing it manually.
X = cv.fit_transform(corpus).toarray()


In [71]:
print(X[:10])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [72]:
print(X.shape)

(1000, 1565)


In [73]:
#here we can see that the 1565 words are taken from the reviews and so we add a new parameter in countVectorizer a max_feature.
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values


In [74]:
print(X.shape)

(1000, 1500)


In [75]:
""" we will train our model to predict of the review. The most common model used in Natual Language Processing are
naive bayes decision tree and random forest. We will use here naive bayes first""" 
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [76]:
print(cm)

[[48 48]
 [18 86]]


In [77]:
from sklearn.metrics import classification_report
target =["negative add", "positive add"]
print(classification_report(y_test, y_pred, target_names=target))

              precision    recall  f1-score   support

negative add       0.73      0.50      0.59        96
positive add       0.64      0.83      0.72       104

   micro avg       0.67      0.67      0.67       200
   macro avg       0.68      0.66      0.66       200
weighted avg       0.68      0.67      0.66       200



In [78]:
a = (48+86)/200

In [79]:
print("accuracy {}\n".format(a))

accuracy 0.67



In [82]:
#Now we will train random forest to the dataset
from sklearn.ensemble import RandomForestClassifier
SEED = 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)
rf = RandomForestClassifier(n_estimators=400, min_samples_leaf=0.12,max_depth = 5,  random_state=SEED)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
from sklearn.metrics import confusion_matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)


[[  0 108]
 [  0  92]]


In [83]:
from sklearn.metrics import classification_report
target =["negative add", "positive add"]
print(classification_report(y_test, y_pred_rf, target_names=target))

              precision    recall  f1-score   support

negative add       0.00      0.00      0.00       108
positive add       0.46      1.00      0.63        92

   micro avg       0.46      0.46      0.46       200
   macro avg       0.23      0.50      0.32       200
weighted avg       0.21      0.46      0.29       200



C:\Users\rahul007\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
